version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 147997150443.dkr.ecr.eu-north-1.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t react-cicd-demo .
      - docker tag react-cicd-demo:latest 147997150443.dkr.ecr.eu-north-1.amazonaws.com/react-cicd-demo:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push 147997150443.dkr.ecr.eu-north-1.amazonaws.com/react-cicd-demo:latest
